print ("Mời bạn nhập vào độ dài tính theo km(làm tròn đến 2 chữ số thập phân):")
f_nhap= input()
f_nhap = float (f_nhap)
f_m=  round (float(f_nhap/1000),2)
f_dm= round (float (f_nhap/10000),2)
f_cm= round (float (f_nhap/100000),2)
f_mm= round (float (f_nhap/1000000),2)
f_mile= round (float(f_nhap/1.609344),2)
f_inch = round (float (f_nhap/39370.1),2)
print ("Quy đổi ra MET là:", f_m)
print ("Quy đổi ra DECIMET là:", f_dm)
print ("Quy đổi ra CENTIMET là:", f_cm)
print ("Quy đổi ra MILIMET là:", f_mm)
print ("Quy đổi ra MILE là:", f_mile)
print ("Quy đổi ra INCH là:", f_inch)